config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount SseRailsEngine::Engine, at: '/sse'
  root 'home#index'
  match 'send_message', to: 'home#send_message', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def send_message
    title = params[:message][:title]
    description = params[:message][:description]
    SseRailsEngine.send_event('test', { title: title, description: description })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= form_for :message, url: send_message_path, remote: true, method: :post do |f| %>
  <div>
  <%= f.label :title %>
  </div>
  <div>
  <%= f.text_field :title %>
  </div>
  <div>
  <%= f.label :description %>
  </div>
  <div>
  <%= f.text_area :description%>
  </div>
  <div>
  <%= f.submit %>
  </div>
<% end %>

<div id="messages">
  <div id="message" style="margin: .5rem; padding: .5rem; border: solid; display: none">
    title:<div id="title"></div>
    message:<div id="description"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>